#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Feb 26 22:07:20 CST 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim adder_testbench_behav -key {Behavioral:sim_1:Functional:adder_testbench} -tclbatch adder_testbench.tcl -log simulate.log"
xsim adder_testbench_behav -key {Behavioral:sim_1:Functional:adder_testbench} -tclbatch adder_testbench.tcl -log simulate.log

